### ISSUE TITLE
Any sorts of outcomes?

### ISSUE THREAD

**Issue by Soooda** [mandy0409/animeInterpolation_research#1]
Hello Melie,

I was looking into AnimeInterp on Github and found your repo by accident. I saw you were trying to combine GMA and NCUP along with AnimeInterp. Just curious how does it end up? :D

Cheers~

**Comment by helloimmelie** [comment]
Hello, I tried to combine NCUP, also GMA to Animeinterp GitHub. 
I will start this project after I finish my graduation project.
Thanks for interests :D

**Comment by Soooda** [comment]
> 

Haha, sure. Thanks for the instant reply. Actually, animation frame interpolation is my thesis project as well. Mind if I carry on your work as I am very eager to know the outcome?

Btw, good luck with ur project! We r both one step away from grad :D

**Comment by helloimmelie** [comment]
Sure! Why not? Please share me the process when you started project. Actually, I think I really need to modify my code a lot, haha... So I will also work on it again, after I finished writing the paper for my graduation. 

Thank you:D

**Comment by Soooda** [comment]
> Sure! Why not? Please share me the process when you started project. Actually, I think I really need to modify my code a lot, haha... So I will also work on it again, after I finished writing the paper for my graduation.
> 
> Thank you:D

Right, I will see what I can. Btw AnimeInterp is in Pytorch 1.1 which is a total nightmare indeed xD

**Comment by helloimmelie** [comment]
Hey! If my memory is right, Animeinterp works fine in pytorch 1.7. 
Anyway, I can provide you the results of SGM module, which takes long time for processing.

**Comment by Soooda** [comment]
> Hey! If my memory is right, Animeinterp works fine in pytorch 1.7. Anyway, I can provide you the results of SGM module, which takes long time for processing.

Really? Coz I was strictly following the README, maybe they did some modifications to the code to work with the later versions. But I had the pipeline running on 1.1 alr. In the meantime, I am worried about the originality of this project since this is clearly ur idea and I cannot steal it from u. I don't know whether doing this as my thesis causes any harm to academic dishonesty. I will consult with my supervisor and let u know ASAP.

**Comment by helloimmelie** [comment]
Since I am researching about stop motion animation interpolation, You can use my idea. I can help with you.

**Comment by helloimmelie** [comment]
Soooda,  I recommend reading my commented issue to Animeinterp's author. 
 https://github.com/lisiyao21/AnimeInterp/issues/24

**Comment by Soooda** [comment]
I think I will start with GMA and AnimeInterp, I'll keep u updated!

**Comment by helloimmelie** [comment]
Thanks, if you need any help. Contact me: mandy0409@cau.ac.kr
